# Generated by Django 5.1.3 on 2024-11-27 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.CharField(max_length=255, verbose_name='возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='имэил')),
                ('phone', models.CharField(max_length=255, verbose_name='возраст')),
            ],
            options={
                'verbose_name': 'UserModel',
                'verbose_name_plural': 'UserModels',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(verbose_name='статус')),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.TextField(verbose_name='описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.usersmodel')),
            ],
            options={
                'verbose_name': 'TaskModel',
                'verbose_name_plural': 'TaskModels',
            },
        ),
    ]
