# Generated by Django 5.1.3 on 2024-11-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
